<?php

declare(strict_types=1);

namespace Common\Domain\Validation\Notification;

enum NOTIFICATION_TYPE: string
{
    case USER_REGISTERED = 'NOTIFICATION_USER_REGISTERED';
    case USER_EMAIL_CHANGED = 'NOTIFICATION_USER_EMAIL_CHANGED';
    case USER_PASSWORD_CHANGED = 'NOTIFICATION_USER_PASSWORD_CHANGED';
    case USER_PASSWORD_REMEMBER = 'NOTIFICATION_USER_PASSWORD_REMEMBER';
    case GROUP_CREATED = 'NOTIFICATION_GROUP_CREATED';
    case GROUP_REMOVED = 'NOTIFICATION_GROUP_REMOVED';
    case GROUP_USER_REMOVED = 'NOTIFICATION_GROUP_USER_REMOVED';
    case GROUP_USER_ADDED = 'NOTIFICATION_GROUP_USER_ADDED';
    case GROUP_USER_SET_AS_ADMIN = 'GROUP_USER_SET_AS_ADMIN';
}
