# -------------------------------------------------------------
# LIST ORDERS CREATE
list_orders_create:
  path: /api/v{api_version}/list-orders
  methods: POST
  controller: ListOrders\Adapter\Http\Controller\ListOrdersCreate\ListOrdersCreateController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS CREATE FROM
# -------------------------------------------------------------
list_orders_create_from:
  path: /api/v{api_version}/list-orders/create-from
  methods: POST
  controller: ListOrders\Adapter\Http\Controller\ListOrdersCreateFrom\ListOrdersCreateFromController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS MODIFY
# -------------------------------------------------------------
list_orders_modify:
  path: /api/v{api_version}/list-orders
  methods: PUT
  controller: ListOrders\Adapter\Http\Controller\ListOrdersModify\ListOrdersModifyController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS GET DATA
# -------------------------------------------------------------
list_orders_get_data:
  path: /api/v{api_version}/list-orders
  methods: GET
  controller: ListOrders\Adapter\Http\Controller\ListOrdersGetData\ListOrdersGetDataController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS GET FIRST LETTER
# -------------------------------------------------------------
list_orders_get_first_letter:
  path: /api/v{api_version}/list-orders/first-letter
  methods: GET
  controller: ListOrders\Adapter\Http\Controller\ListOrdersGetFirstLetter\ListOrdersGetFirstLetterController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS REMOVE
# -------------------------------------------------------------
list_orders_remove:
  path: /api/v{api_version}/list-orders
  methods: DELETE
  controller: ListOrders\Adapter\Http\Controller\ListOrdersRemove\ListOrdersRemoveController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS REMOVE ALL GROUP LIST OF ORDERS
# -------------------------------------------------------------
list_order_remove_all_group_id_and_change_user_id:
  path: /api/v{api_version}/list-orders/group/remove-change
  methods: DELETE
  controller: ListOrders\Adapter\Http\Controller\ListOrdersRemoveAllGroupsListsOrders\ListOrdersRemoveAllGroupsListsOrdersController
  requirements:
    api_version: '\d+[.\d]?'

# -------------------------------------------------------------
# LIST ORDERS GET PRICE
# -------------------------------------------------------------
list_orders_get_price:
  path: /api/v{api_version}/list-orders/price
  methods: GET
  controller: ListOrders\Adapter\Http\Controller\ListOrdersGetPrice\ListOrdersGetPriceController
  requirements:
    api_version: '\d+[.\d]?'
