imports:
    - {
          resource: "../../../../../User/Adapter/Framework/Config/packages/twig.yaml",
      }

twig:
    default_path: "%kernel.project_dir%/templates"

when@test:
    twig:
        strict_variables: true
