doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Share:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Share/Adapter/Database/Orm/Doctrine/Mapping"
                prefix: 'Share\Domain\Model'
                alias: Share
