name: Main push

on:
  push:
    branches:
      - main

concurrency:
  group: main-on-push
  cancel-in-progress: true

jobs:
  # ---------------------------------------
  # Sets the application up for production
  # --------------------------------------
  setup-production:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Clone repository
        uses: actions/checkout@v4.1.7

      # Composer cache
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setting up project for deploy
        run: |
          cd $GITHUB_WORKSPACE
          make setup-deploy
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_VERSION: ${{ secrets.DB_VERSION }}
          MAILER_DSN: ${{ SECRETS.MAILER_DSN }}

      - name: Create application artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-production-artifact
          path: .
          overwrite: true

  # --------------------------------------
  # Deploy application on server
  # --------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: setup-production

    steps:
      - name: Get application artifact
        uses: actions/download-artifact@v4
        with:
          name: app-production-artifact
          path: .

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: ""
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: "-rlgoDzvc --delete --exclude='public/assets/img/users/' --exclude='public/assets/img/groups/' --exclude='public/assets/img/products/' --exclude='public/assets/img/shops/'"

      - name: Create entrypoint symbol
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            mkdir -p ${{ secrets.DEPLOY_PUBLIC_PATH }}
            ln -sfn ${{ secrets.DEPLOY_PATH }}/public ${{ secrets.DEPLOY_PUBLIC_PATH }}/api
            ln -sfn ${{ secrets.DEPLOY_PATH }}/public/index.php ${{ secrets.DEPLOY_PUBLIC_PATH }}/index_api.php
            cp ${{ secrets.DEPLOY_PATH }}/../config/OrderList-api/AppConfig.php ${{ secrets.DEPLOY_PATH }}/src/Common/Domain/Config/AppConfig.php
            cp ${{ secrets.DEPLOY_PATH }}/../config/OrderList-api/VALUE_OBJECTS_CONSTRAINTS.php ${{ secrets.DEPLOY_PATH }}src/Common/Domain/Model/ValueObject/Constraints/VALUE_OBJECTS_CONSTRAINTS.php
            chmod -R 744 ${{ secrets.DEPLOY_PATH }}
            chmod -R 766 ${{ secrets.DEPLOY_PATH }}/public/assets
            chmod 644 ${{ secrets.DEPLOY_PATH }}/public/assets/.htaccess
