name: Main push

on:
  push:
    branches:
      - main

concurrency:
  group: main-on-push
  cancel-in-progress: true

jobs:

  # ---------------------------------------
  # Sets the application up for production
  # --------------------------------------
  setup-production:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Clone repository
        uses: actions/checkout@v4.1.7

      - name: Setting up project for deploy
        run: |
          cd $GITHUB_WORKSPACE
          make setup-deploy
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_VERSION: ${{ secrets.DB_VERSION }}


  # --------------------------------------
  # Deploy application on server
  # --------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: setup-production

    steps:
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: ""
          TARGET: ${{ secrets.DEPLOY_PATH }}
          ARGS: "-rlgoDzvc --delete"