name: Execute tests

on:
  - push

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    
    steps: 
      - name: "Clone repository"
        uses: actions/checkout@v4
          with: 
            repository: 'Victor-codigo/OrderList-api'
            ref: 'test'

      - name: "Setup docker"
        run: cd .docker \
             make up
            
